:seedling: Feature/login
Balanced02/bookry-client pull request #17
Opened 2022-08-10 02:36 UTC by sammysmart95

- Add Sign In page with full functionality
- Add Sign In hook with full functionality

2022-08-12 12:25 UTC, donskilful requested changes
- print actual error when a user tries to register with existing email
- print an error if the user did not check the check box which says: i agree to terms and conditions 
- Make the password eye checker functional
- After successful sign up redirect to sign in screen

2022-08-15 20:39 UTC, sammysmart95 commented on src/modules/Auth/hooks/useSignin.ts
> +        showSuccess({ title: 'Login Successful!', description: 'You are too good' });
Resolved

2022-08-15 20:39 UTC, sammysmart95 commented on src/modules/Auth/hooks/useSignin.ts
> +        showError({ title: 'Login Error', description: "You're a dummy" });
Resolved

2022-08-16 03:47 UTC, donskilful requested changes
implement complete design

2022-08-21 16:26 UTC, donskilful requested changes
After Successful Sign up it should route to Sign in
If account already exist it does not toast any notification i have to open console to see the error

2022-08-21 16:27 UTC, donskilful requested changes
Add an effect on the Sign up and Sing in button when a user clicks and hovers

2022-08-24 11:47 UTC, merged